DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS stocks CASCADE;
DROP TABLE IF EXISTS users_stocks CASCAE;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL
);

CREATE TABLE stocks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  symbol VARCHAR(10) NOT NULL, 
  company VARCHAR(1000),
  price BIGINT
);

-- CREATE TABLE users_stocks (
--   user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
--   stock_id BIGINT REFERENCES stocks(id) ON DELETE CASCADE,
--   PRIMARY KEY(user_id, stock_id)
-- );
